---
title: "Trajectory_inference_analysis"
author: "Roger Casals"
date: "2025-01-22"
output: html_document
---

# Load libraries

```{r include=FALSE}

library(Seurat)
library(SeuratWrappers)
library(monocle3)
library(ggplot2)
library(tidyr)
library(dplyr)
library(tidyverse)
library(SingleCellExperiment)
library(SeuratData)
library(SeuratDisk)
library(AnnotationDbi)
library(dittoSeq)
library(tidyverse)
library(msigdbr)
library(clusterProfiler)
library(fgsea)
library(org.Hs.eg.db)


```


# Read Seurat Objects

```{r include=FALSE}

CD4 <- LoadH5Seurat("/home/roger/Baixades/totscd8.h5seurat")
CD4pre <- LoadH5Seurat("/home/roger/Baixades/precd8.h5seurat")
#CD4pre <- LoadH5Seurat("/home/roger/Baixades/postcd8.h5seurat")
```




## Learn trajectory
We use Monocle3 package to learn the trajectory. 

```{r}
# This example if for "pre-treatment conditions". But you can play with any comparision. 

set.seed(123)
CD4pre@meta.data$cluster_redefined <- CD4pre@meta.data$cluster

cds_object <- as.cell_data_set(CD4pre) # transform seurat to cell data object (input for monocle)
cds_object <- cluster_cells(cds_object, reduction_method = "UMAP", )  # Cluster cells (necessary to learn graph)
cds_object <- learn_graph(cds_object, use_partition = FALSE, learn_graph_control = list(euclidean_distance_ratio=2, minimal_branch_len=5, prune_graph=TRUE)) # Learn graph on an unsupervised manner. 
# Some parameters to check 


cds_object@clusters$UMAP$clusters <- CD4pre@active.ident

cds_object <- order_cells(cds_object, reduction_method = 'UMAP', root_cells = colnames(cds_object[,clusters(cds_object) == "pre_CD8_Naive"]))  # We set up the root as naive cells.

# Use plot_cells() to see the trajectory. 
plot_cells(cds_object)

# Extract pseudotime values and closest nodes for each cell. Add into Seurat's object for further pre-processing
cds_object$monocle3_pseudotime <- pseudotime(cds_object)
cds_object@colData$closest_node <- principal_graph_aux(cds_object)$UMAP$pr_graph_cell_proj_closest_vertex

```



# Find DE genes for each differentiation branch
We select the cells that are on each branch, we compute a Wilcoxon test on Seurat function to detect those genes. 

```{r}
# Identify the nodes that correspond to each branch and do posterior analysis
cds_subset <- choose_cells(cds_object) #Subset cells
subset_seurat_obj <- subset(CD4pre, cells = colnames(cds_subset))  # Subset Seurat object
cell_names <- data.frame(CellNames = colnames(subset_seurat_obj))

markers <- FindMarkers(subset_seurat_obj, ident.1=c("pre_CD8_ex", ident.2=c("pre_CD8_ex_act")))  # Find DE genes based on Wilcoxon test based on the different conditions.
markers <- subset(markers, p_val_adj < 0.05 & abs(avg_log2FC) > 1) # Subset only the adjusted significative genes.
markers$gene <- row.names(markers)
markers$diff <- markers$pct.1 - markers$pct.2

#Idents(subset_seurat_obj) <- "RNA_snn_res.0.3"
#markers <- FindMarkers(subset_seurat_obj, ident.1=c("8"), ident.2=c("1"))  # Find DE genes based on Wilcoxon test based on the different conditions.


# Repeat for all the 10 branches identified, and for the different conditions. 
# Save gene list and Seurat objects for reproducibility. 
write.csv(markers, file = "/home/roger/data_immunotherapy/DEgenes/branch7.csv", row.names = FALSE)
write.csv(cell_names, file = "/home/roger/data_immunotherapy/cell_names/branch7.csv", row.names = FALSE)

```


