---
title: "Preprocess"
author: "Roger Casals"
date: "2023-05-29"
output: html_document
---


# Load libraries
```{r}
library(Seurat)
library(data.table)
library(SeuratDisk)
```
Load the data from GSE123813 repository. Using Squamous Cell Carcinoma (SCC)

```{r}
#  Load counts matrix and metadata
expression_df <- fread("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE123813&format=file&file=GSE123813%5Fscc%5FscRNA%5Fcounts%2Etxt%2Egz")
metadata <- fread("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE123813&format=file&file=GSE123813%5Fscc%5Fmetadata%2Etxt%2Egz")

# Convert to data.frame to assign row.names
expression_df <- as.data.frame(expression_df)
rownames(expression_df) <- expression_df[[1]]
expression_df <- expression_df[ , -1]

# Order metadata and expression_df
expression_df <- expression_df[, order(colnames(expression_df))]
metadata <- metadata[order(metadata$cell.id),]
```

## Preprocessing using Seurat

```{r}
# Create Seurat Object
# Add that the min cells should be 5, and the min genes x cell 200.
seurat <- CreateSeuratObject(counts=expression_df, project="GSE123813", meta.data=metadata, min.cells = 5, min.features = 200)
```

#### Quality Control (QC)
```{r}
#Obtain mitochondrial and ribosomal percentages.
seurat <- PercentageFeatureSet(seurat, "^MT-", col.name="percent_mito")
seurat <- PercentageFeatureSet(seurat, "^RP[SL]", col.name = "percent_ribo")
seurat <- PercentageFeatureSet(seurat, "^HB[^(P)]", col.name = "percent_hb")

feats <- c("nFeature_RNA", "nCount_RNA", "percent_mito", "percent_ribo", "percent_hb")

VlnPlot(seurat, group.by = "cluster", features = feats, pt.size = 0.1, ncol = 3) +
    NoLegend()

FeatureScatter(seurat, "nCount_RNA", "nFeature_RNA", group.by = "cluster", pt.size = 0.5)

# Subset after looking at distributions
seurat <- subset(seurat, subset=nFeature_RNA < 4000 & nFeature_RNA > 1000 & percent_mito < 8 & nCount_RNA < 12000)

# Add pre and post cell types
seurat$celltype.cnd <- paste0(seurat$treatment, "_", seurat$cluster) 

```
# Subset CD8 T cells for further analysis.

```{r}

unique(seurat@meta.data$cluster)

# Subset CD8 cells.
CD8 <- subset(seurat, cluster %in% c("CD8_ex", "CD8_mem", "CD8_eff", "CD8_naive", "CD8_ex_act", "CD8_act"))

CD8 <- NormalizeData(CD8)  # normalize data
CD8 <- FindVariableFeatures(CD8, selection.method = "vst", nfeatures = 2000)  # select hvg
CD8 <- ScaleData(CD8)   # scale data
CD8 <- RunPCA(CD8, npcs = 16)   # compute PCA
CD8 <- FindNeighbors(CD8, dims = 1:16)   # Find neighbors

CD8 <- FindClusters(CD8, resolution = c(0.7))  # Find best resolution clustering
CD8 <- RunUMAP(CD8, dims=1:16)

DimPlot(CD8, reduction = "umap", group.by = "treatment")  # visualize data
DimPlot(CD8, reduction="umap", group.by="cluster", label=T)

# Remove cluster 12 that we do not know what is that.
DimPlot(CD8, reduction="umap", group.by="RNA_snn_res.0.7", label=T)
CD8 <- subset(CD8, subset = `RNA_snn_res.0.7` != 12)

# We look at the number of cells after QC, those are the cells that we will use for downstream analysis
table(CD8@meta.data$patient, CD8@meta.data$celltype.cnd)

```

# Save objects
```{r}

Idents(CD8) <- "celltype.cnd"

CD8pre <- subset(CD8, celltype.cnd %in% c("pre_CD8_act", "pre_CD8_eff", "pre_CD8_ex", "pre_CD8_ex_act", "pre_CD8_mem", "pre_CD8_Naive"))
CD8post <- subset(CD8, celltype.cnd %in% c("post_CD8_act", "post_CD8_eff", "post_CD8_ex", "post_CD8_ex_act", "post_CD8_mem", "post_CD8_Naive"))

SaveH5Seurat(CD8, "totscd8", overwrite=FALSE, verbose=TRUE)
SaveH5Seurat(CD8pre, "precd8", overwrite=FALSE, verbose=TRUE)
SaveH5Seurat(CD8post, "postcd8", overwrite=FALSE, verbose=TRUE)
```

# Subset CD4 T cells for further analysis.

```{r}
# Subset CD4 cells.
CD4 <- subset(seurat, cluster %in% c("Treg", "Tfh", "Naive", "Th17"))

CD4 <- NormalizeData(CD4)  # normalize data
CD4 <- FindVariableFeatures(CD4, selection.method = "vst", nfeatures = 2000)  # select hvg
CD4 <- ScaleData(CD4)   # scale data
CD4 <- RunPCA(CD4, npcs = 16)   # compute PCA
CD4 <- FindNeighbors(CD4, dims = 1:16)   # Find neighbors

CD4 <- FindClusters(CD4, resolution = c(0.7))  # Find best resolution clustering
CD4 <- RunUMAP(CD4, dims=1:16, n.neighbors = 50, min.dist = 0.1)

DimPlot(CD4, reduction = "umap", group.by = "treatment")  # visualize data
DimPlot(CD4, reduction="umap", group.by="cluster")
DimPlot(CD4, reduction="umap", group.by="RNA_snn_res.0.7", label=T)


```


```{r}

Idents(CD4) <- "celltype.cnd"

CD4pre <- subset(CD4, celltype.cnd %in% c("pre_Naive", "pre_Th17", "pre_Treg", "pre_Tfh"))

CD4post <- subset(CD4, celltype.cnd %in% c("post_Naive", "post_Th17", "post_Treg", "post_Tfh"))


# Generate figures.
p <- DimPlot(
  CD4pre,
  reduction = "umap",
  group.by = "cluster",
  pt.size = 2.5
)

p + scale_color_manual(values = c(
  Naive = "skyblue",
  Treg  = "red",
  Tfh   = "purple",
  Th17  = "green"
))

ggsave("cd4_umap_pre.svg", plot = last_plot(),
       width = 6, height = 6, units = "in",
       device = svglite::svglite, bg = "transparent")

p <- DimPlot(
  CD8post,
  reduction = "umap",
  group.by = "cluster",
  pt.size = 2.5
)

p + scale_color_manual(values = c(
  Naive = "skyblue",
  Treg  = "red",
  Tfh   = "purple",
  Th17  = "green"
))

ggsave("cd4_umap_post.svg", plot = last_plot(),
       width = 6, height = 6, units = "in",
       device = svglite::svglite, bg = "transparent")
```


# Save objects

```{r}

SaveH5Seurat(CD4, "tots", overwrite=FALSE, verbose=TRUE)
SaveH5Seurat(CD4pre, "pre", overwrite=TRUE, verbose=TRUE)
SaveH5Seurat(CD4post, "post", overwrite=FALSE, verbose=TRUE)

```

# Number of cells that we are going to analyse.

```{r}

table(CD4@meta.data$patient, CD4@meta.data$celltype.cnd)

```








