---
title: "Total"
author: "Roger Casals"
date: "2023-05-29"
output: html_document
---



Load the data from SCC

# Squamos cell carcionma 

```{r}
#  you can load data from GEO repository
expression_data <- fread("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE123813&format=file&file=GSE123813%5Fscc%5FscRNA%5Fcounts%2Etxt%2Egz")
metadata2 <- fread("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE123813&format=file&file=GSE123813%5Fscc%5Fmetadata%2Etxt%2Egz")


# Set working directory
#setwd("C:/Users/Roger Casals/OneDrive/Escriptori/UOC ROGER/2n semestre/TFM/Final 5_5")
setwd("C:/Users/Natàlia/Desktop/UOC ROGER/2n semestre/TFM/Primera prova")

# Load metadata and counts
metadata2 <- data.table::fread("GSE123813_scc_metadata.txt.gz")
expression_data <- read.table("GSE123813_scc_scRNA_counts.txt.gz", header=TRUE, row.names=1, sep="\t", check.names=FALSE)

```



## Load libraries


```{r}
library(Seurat)
library(SeuratWrappers)
library(monocle3)
library(ggplot2)
library(tidyr)
library(dplyr)
library(dyno)
library(tidyverse)
library(dynwrap)
library(SingleCellExperiment)
library(dyneval)

```




## Preprocessing using Seurat

### Seurat object

```{r}


aa <- CreateSeuratObject(counts=expression_data, project="GSE123813", metadata=metadata2)

bbb <- aa



# Sort metadata

metadata2 <- metadata2[order(metadata2$cell.id),]
aa <- aa[, order(colnames(aa))]
aa@meta.data <- aa@meta.data[order(row.names(aa@meta.data)), ]



```




### Add metadata to Seurat

```{r}

aa@meta.data$cluster <- metadata2$cluster
aa@meta.data$treatment <- metadata2$treatment


table(aa@meta.data$cluster)

```




#### Quality Control (QC)

```{r}

#Obtain mitochondrial and ribosomal percentages.
aa <- PercentageFeatureSet(aa, "^MT-", col.name="percent_mito")
aa <- PercentageFeatureSet(aa, "^RP[SL]", col.name = "percent_ribo")
aa <- PercentageFeatureSet(aa, "^HB[^(P)]", col.name = "percent_hb")

feats <- c("nFeature_RNA", "nCount_RNA", "percent_mito", "percent_ribo", "percent_hb")

VlnPlot(aa, group.by = "orig.ident", features = feats, pt.size = 0.1, ncol = 3) +
    NoLegend()

FeatureScatter(aa, "nCount_RNA", "nFeature_RNA", group.by = "orig.ident", pt.size = 0.5)


CD4tots <- aa

pre.markers <- FindAllMarkers(CD8tots ,only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)


pre.markers %>%
    group_by(cluster) %>%
    top_n(n = 3, wt = avg_log2FC) -> top15
DoHeatmap(CD8tots, features = top15$gene, size=2)



unique(aa@meta.data$cluster)

CD8tots <- subset(aa, cluster %in% c("CD8_ex", "CD8_mem", "CD8_eff", "CD8_naive", "CD8_ex_act", "CD8_act"))

CD4tots <- CD8tots

CD4tots <- subset(CD4tots, subset=nFeature_RNA < 4000 & percent_mito < 8 )

table(CD4tots@meta.data$cluster)


CD4tots <- NormalizeData(CD4tots)  # normalize data
CD4tots <- FindVariableFeatures(CD4tots, selection.method = "vst", nfeatures = 2000)  # select hvg
CD4tots <- ScaleData(CD4tots)   # scale data
CD4tots <- RunPCA(CD4tots, npcs = 16)   # compute PCA
CD4tots <- FindNeighbors(CD4tots, dims = 1:16)   # Find neighbors

CD4tots <- FindClusters(CD4tots, resolution = c(0.7))  # Find best resolution clustering
CD4tots <- RunUMAP(CD4tots, dims=1:16)

DimPlot(CD4tots, reduction = "umap", group.by = "treatment")  # visualize data
DimPlot(CD4tots, reduction="umap", group.by="cluster", label=T)

```


### Identify cell types between treatment conditions


```{r}
CD4totssubset$celltype.cnd <- paste0(CD4totssubset$treatment, "_", CD4totssubset$idents)  # Add '-' to separate 
```

```{r}

# Calculate proportions of each cell type.
prop.table(table(CD4totssubset@meta.data$celltype.cnd))*100
table(CD4totssubset@meta.data$celltype.cnd)

```


# Save objects

```{r}

CD8totssubset <- CD4totssubset
CD8totssubsetpre <- subset(CD8totssubset, celltype.cnd %in% c("pre_CD8_act", "pre_CD8_eff", "pre_CD8_ex", "pre_CD8_ex_act", "pre_CD8_mem", "pre_CD8_Naive"))
CD8totssubsetpost <- subset(CD8totssubset, celltype.cnd %in% c("post_CD8_act", "post_CD8_eff", "post_CD8_ex", "post_CD8_ex_act", "post_CD8_mem", "post_CD8_Naive"))

#SaveH5Seurat(CD8totssubset, "totscd8", overwrite=FALSE, verbose=TRUE)
#SaveH5Seurat(CD8totssubsetpre, "precd8", overwrite=FALSE, verbose=TRUE)
#SaveH5Seurat(CD8totssubsetpost, "postcd8", overwrite=FALSE, verbose=TRUE)


```






















